server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/LiveVideo?serverTimeZone=GMT%2b8
    #    url: jdbc:mysql://localhost:3306/test_db?serverTimeZone=GMT%2b8
    username: root
    #    password: 123456
    password: root
  mail:
    host: smtp.163.com
    username: livevideo2022@163.com
    password: WAOIDFQQGHOMLJGT
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: false
        debug: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

src:
  video-path: src/main/resources/static/video/
  picture-path: src/main/resources/static/picture/


#logging:
#  level:
#    com.example.live_video.mapper: debug


mybatis:
  #用于mybatis在控制台打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
